### ISSUE TITLE
What's the motivation of the repository

### ISSUE THREAD

**Issue by RuoyuChen10** [gaojunbin/visual_pts#1]
Can you offer more codes or examples to better understand your work?

**Comment by gaojunbin** [comment]
> Can you offer more codes or examples to better understand your work?

Existing point cloud visualization tools(e.g. Open3D, mayavi, etc.) are either very inflexible to use, or complicated to install, which hinders the progress of research. This tool aims to help us visualize 3D point clouds  easily while developing.
